Conf validation
neo9/n9-node-routing pull request #47
Opened 2022-12-04 22:29 UTC by vloic07

2022-12-06 14:30 UTC, BenjD90 requested changes
I have just reviewed the tests for now

2022-12-06 14:30 UTC, BenjD90 commented on test/micro-foo.test.ts
> +	t.true(output[1].includes('Configuration validation is disabled'));
Here the message related to the assertion is missing. This is helpfull to debug tests errors.

2022-12-06 14:30 UTC, BenjD90 commented on test/micro-conf-validation.test.ts
> +	t.true(errors.context.validationErrors[0].constraints.isNumber.includes('bar must be a number'));
Please add messages to assetions.

2022-12-06 14:30 UTC, BenjD90 commented on test/micro-conf-validation.test.ts
> +ava('Should not proceed any validation - validation is disabled', async (t: Assertions) => {
Could you add the same test but with deactivation of the validation from the configuration itself, in configuration extension for example ?

2022-12-06 17:24 UTC, vloic07 commented on test/micro-foo.test.ts
> +	t.true(output[1].includes('Configuration validation is disabled'));
Done

2022-12-06 17:24 UTC, vloic07 commented on test/micro-conf-validation.test.ts
> +	t.true(errors.context.validationErrors[0].constraints.isNumber.includes('bar must be a number'));
Done

2022-12-07 10:15 UTC, vloic07 commented on test/micro-conf-validation.test.ts
> +ava('Should not proceed any validation - validation is disabled', async (t: Assertions) => {
Done

2022-12-07 16:41 UTC, vhugues commented on package.json
> +    "@types/lodash": "^4.14.170",
@types/lodash doit être dans les dev-dependencies
[Facultatif]
"@types/cls-hooked" et "@types/node" doivent l'être aussi

2022-12-07 16:41 UTC, vhugues commented on src/express-app.ts
> +		await options.http.beforeRoutingControllerLaunchHook(expressApp, log, options, conf);
Il commence à y avoir trop de param (qui n'ont pas d'ordre logique).  
À convertir en objet / ou créé un ticket pour ça.

2022-12-07 16:41 UTC, vhugues commented on src/express-app.ts
> +		await options.http.afterRoutingControllerLaunchHook(expressApp, log, options, conf);
idem

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/options.ts
> +	log?: N9Log;
N9Log n'est pas une class avec validateur, le ValidateNested est inutile

2022-12-07 16:41 UTC, vhugues commented on src/index.ts
> +	(global as any).conf = conf;
On ne devrait pas utiliser la version "plain" de là conf, mais plutôt une instance de class (qui a été générer dans la fonction validateConf) car sinon on se balade sans les transformations qui on était appliqué et validé.

2022-12-07 16:41 UTC, vhugues commented on src/init-conf.ts
> +	if (validationOptions.isEnabled && !validationOptions.classType) {
```suggestion
	if (!validationOptions.classType) {
```

2022-12-07 16:41 UTC, vhugues commented on src/models/class-type.models.ts
> +export type ClassType<T> = new (...args: any[]) => T;
[Facultatif]
C'est peut-être l'occasion d'utiliser [type-fest](https://github.com/sindresorhus/type-fest)

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/base-conf.ts
> +	env?: string;
```suggestion
	@IsString()
	env: string;
```

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/base-conf.ts
> +	name?: string;
unused

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/base-conf.ts
> +	version?: string;
unused

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/base-conf.ts
> +	env?: string;
Unused (sauf pour un log, mais qui n'a rien à voir avec l'env)

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/implementations/n9-node-conf.implementation.ts
> +	 */
```suggestion
```

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/implementations/n9-node-conf.implementation.ts
> +	value: object;
```suggestion
	value: ConfType;
```

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/options-http.ts
> +	routingController?: RoutingControllersOptions;
To do

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/options-sentry.ts
> +	initOptions?: Sentry.NodeOptions; // dsn can be provided through env variable
To do

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/options-sentry.ts
> +export class SentryIntegrationTracingOption extends SentryIntegrationOption {
```suggestion
export class SentryIntegrationTracingConfig extends SentryIntegrationConfig {
```

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/options-sentry.ts
> +export class SentryIntegrationTracingOptionMethods {
```suggestion
export class SentryIntegrationTracingOptionsConfig {
```

2022-12-07 16:41 UTC, vhugues commented on src/models/routing/options-sentry.ts
> +	requestHandlerOptions?: RequestHandlerOptions;
To do

2022-12-07 16:41 UTC, vhugues commented on test/fixtures/commons.ts
> +export const minimalOptions: N9NodeRouting.Options = {
```suggestion
export const nodeRoutingMinimalOptions: N9NodeRouting.Options = {
```

2022-12-07 16:41 UTC, vhugues commented on test/fixtures/commons.ts
> +export const defaultConfOptions: N9NodeRouting.ConfOptions = {
```suggestion
export const defaultNodeRoutingConfOptions: N9NodeRouting.ConfOptions = {
```

2022-12-07 16:41 UTC, vhugues commented on test/fixtures/micro-conf-validation/configuration-invalid/conf/integration.ts
> +export default conf;
unused

2022-12-07 16:41 UTC, vhugues commented on test/http-client.test.ts
> +		stdout[5].includes(
On ne devrait pas avoir à spécifier la ligne d'apparition du log.
Des utiles pourraient être utiles pour ce genre de test :  
```typescript
assertLog(t, "Retry call [GET http://localhost:6001/503] n°1 due to HTTPError Response code 503 (Service Unavailable)");

assertLogOrder(t, ["Line3", "line4", "line8"]);
```
Ça évita d'avoir à modifier les tests pour des changements qui n'ont rien avoir avec l'objectif du test.

2022-12-07 16:47 UTC, vloic07 commented on package.json
> +    "@types/lodash": "^4.14.170",
Done

2022-12-07 16:52 UTC, vloic07 commented on src/models/routing/options.ts
> +	log?: N9Log;
Done

2022-12-07 17:05 UTC, vloic07 commented on src/index.ts
> +	(global as any).conf = conf;
La fonction validateConf renvoit maintenant l'instance de conf. Dans l'index.ts, s'il y a une instance de conf alors je l'injecte sinon je prends la conf sous forme plain.
Done

2022-12-07 17:07 UTC, vloic07 commented on src/init-conf.ts
> +	if (validationOptions.isEnabled && !validationOptions.classType) {
Done

2022-12-07 17:13 UTC, vloic07 commented on src/models/class-type.models.ts
> +export type ClassType<T> = new (...args: any[]) => T;
Done

2022-12-07 17:16 UTC, vloic07 commented on src/models/routing/base-conf.ts
> +	env?: string;
Je suis d'accord mais c'est un refacto de n9-node-conf qui est pas bien conçu

2022-12-07 17:18 UTC, vloic07 commented on src/models/routing/base-conf.ts
> +	name?: string;
Same

2022-12-07 17:18 UTC, vloic07 commented on src/models/routing/base-conf.ts
> +	version?: string;
Same https://github.com/neo9/n9-node-routing/pull/47#discussion_r1042479528

2022-12-07 17:19 UTC, vloic07 commented on src/models/routing/implementations/n9-node-conf.implementation.ts
> +	 */
Done

2022-12-08 07:52 UTC, vloic07 commented on src/models/class-type.models.ts
> +export type ClassType<T> = new (...args: any[]) => T;
En fait, je ne peux pas utiliser type-fest car la version minimale requise de node est la version 14 alors que n9NodeRouting supporte jusqu'à la version 12. @BenjD90 Qu'est ce que je fais ?

2022-12-08 07:55 UTC, vloic07 commented on src/models/routing/implementations/n9-node-conf.implementation.ts
> +	value: object;
Done

2022-12-08 08:45 UTC, BenjD90 commented on src/models/class-type.models.ts
> +export type ClassType<T> = new (...args: any[]) => T;
Change la version minimale requise, ce sera une version majeure de toute façon puisque breaking change

2022-12-08 09:26 UTC, BenjD90 commented on src/index.ts
> -export * from './models/routing.models';
This part should still be exported, maybe as N9NodeRouting to replace namespace usage

2022-12-08 09:29 UTC, BenjD90 commented on src/init-conf.ts
> +			validationErrors: validationErrorsWithoutExcludeProperties,
Attention à ne pas mettre un objet complexe en content de logger. 

```suggestion
			argString: JSON.stringify(validationErrorsWithoutExcludeProperties),
```

Idem pour les autres usages

2022-12-08 09:47 UTC, BenjD90 commented on src/models/routing/options.ts
> +	jwt?: JWTOptions;
seams unused, could you delete it ?

2022-12-08 09:50 UTC, BenjD90 commented on src/models/routing/options-sentry.ts
> +export class SentryIntegrationTracingOptionMethods {
```suggestion
export class SentryOptionsAdditionalIntegrationsOptions {
```

2022-12-08 09:50 UTC, BenjD90 commented on src/models/routing/options-sentry.ts
> +export class SentryIntegrationTracingOption extends SentryIntegrationOption {
```suggestion
export class SentryOptionsAdditionalIntegrations extends SentryIntegrationOption {
```

2022-12-08 09:53 UTC, BenjD90 commented on src/models/routing/options-swagger.ts
> +	// TODO: Rename this attribute to isEnabled
à intégrer pour regrouper les breaking changes

2022-12-08 10:01 UTC, BenjD90 commented on src/options.ts
> +					const formatLogInJSON: boolean = options.enableLogFormatJSON;
```suggestion
					const formatLogInJSON: boolean = options.log.formatJSON;
```
ça me semble plus cohérent de se baser sur ce qui a été décidé par l'init du logger

2022-12-08 10:03 UTC, BenjD90 commented on test/fixtures/commons.ts
> +		path: join(__dirname, 'micro-conf-validation/configuration-valid/conf'),
```suggestion
		path: join(__dirname, 'common-conf-validation/configuration-valid/conf'),
```

2022-12-08 10:12 UTC, vloic07 commented on src/models/class-type.models.ts
> +export type ClassType<T> = new (...args: any[]) => T;
J'ai ajouté type-fest. J'ai mis à jour la version minimale de node. J'ai aussi monté la version de typescript à la version 4.9.3 et j'ai du changé quelques dépendances pour que ça fonctionne bien.

Done

2022-12-08 10:13 UTC, vloic07 commented on src/models/routing/options-http.ts
> +	routingController?: RoutingControllersOptions;
Done

2022-12-08 10:14 UTC, vloic07 commented on src/models/routing/options-sentry.ts
> +	initOptions?: Sentry.NodeOptions; // dsn can be provided through env variable
J'ai ajouté une implémentation. Je ne suis pas aller jusqu'au bout car les interfaces sont très profondes et je pense que ce n'est pas utile d'aller si loin pour l'instant. L'objectif étant principalement de valider notre conf.

2022-12-08 10:18 UTC, vloic07 commented on src/models/routing/options-sentry.ts
> +export class SentryIntegrationTracingOption extends SentryIntegrationOption {
J'ai pris la solution de Benjamin.

Done

2022-12-08 10:19 UTC, vloic07 commented on src/models/routing/options-sentry.ts
> +export class SentryIntegrationTracingOptionMethods {
Done

2022-12-08 10:19 UTC, vloic07 commented on src/models/routing/options-sentry.ts
> +	requestHandlerOptions?: RequestHandlerOptions;
C'était un type derrière. J'ai mis un Allow() est ce que ça te va ?

2022-12-08 10:39 UTC, vloic07 commented on test/fixtures/commons.ts
> +export const minimalOptions: N9NodeRouting.Options = {
Done

2022-12-08 10:39 UTC, vloic07 commented on test/fixtures/commons.ts
> +export const defaultConfOptions: N9NodeRouting.ConfOptions = {
Done

2022-12-08 11:08 UTC, vloic07 commented on src/express-app.ts
> +		await options.http.beforeRoutingControllerLaunchHook(expressApp, log, options, conf);
Je ne peux pas créer de ticket puisqu'il n'y a pas de jira et je ne vais pas le faire dans cette carte. Je reste sur le fonctionnement actuel même si je suis d'accord avec toi. Est ce que ça te va ?

2022-12-08 11:09 UTC, vloic07 commented on src/express-app.ts
> +		await options.http.afterRoutingControllerLaunchHook(expressApp, log, options, conf);
Pareil https://github.com/neo9/n9-node-routing/pull/47#discussion_r1043233733

2022-12-08 11:10 UTC, vloic07 commented on test/fixtures/micro-conf-validation/configuration-invalid/conf/integration.ts
> +export default conf;
J'ai retiré tous les environnements non utilisés.
Done.

2022-12-08 11:11 UTC, vloic07 commented on test/http-client.test.ts
> +		stdout[5].includes(
Je suis d'accord avec toi. Mais sur cette carte, je reste sur le fonctionnement initial. On pourra créer une carte quand il y aura un Jira associé.

2022-12-08 11:13 UTC, vloic07 commented on src/index.ts
> -export * from './models/routing.models';
I don't get what you mean. Validators are still exported in the same way as before and all models that were previously in the namespace are exported as N9NodeRouting from the module './models/routing'. Nothing as changed to me.

2022-12-08 11:18 UTC, vloic07 commented on src/init-conf.ts
> +			validationErrors: validationErrorsWithoutExcludeProperties,
Je ne comprends pas ce que ça change. Peux tu m'expliquer ?
Je préfère le système de logger décider de ce qu'il veut faire. En plus, c'est le résultat d'un classToPlain, l'objet est déjà un plain donc moins complexe.

2022-12-08 11:22 UTC, vloic07 commented on src/models/routing/options.ts
> +	jwt?: JWTOptions;
Done

2022-12-08 11:25 UTC, vloic07 commented on src/models/routing/options-swagger.ts
> +	// TODO: Rename this attribute to isEnabled
Je ne suis pas d'accord. Il faut une autre carte. Ma carte est déjà beaucoup plus grosse que prévu, je ne veux pas que ça devienne un prétexte pour faire d'autres changements.
Mais je reste d'accord avec ce que tu dis, je veux juste une autre carte pour le faire et je le ferai de suite.

2022-12-08 11:28 UTC, vloic07 commented on src/models/routing/options-swagger.ts
> +	// TODO: Rename this attribute to isEnabled
Après vérification ça reste petit, je vais le faire

2022-12-08 11:29 UTC, vloic07 commented on src/options.ts
> +					const formatLogInJSON: boolean = options.enableLogFormatJSON;
Done

2022-12-08 11:41 UTC, vloic07 commented on src/models/routing/options-swagger.ts
> +	// TODO: Rename this attribute to isEnabled
Done

2022-12-13 08:08 UTC, vloic07 commented on test/fixtures/commons.ts
> +		path: join(__dirname, 'micro-conf-validation/configuration-valid/conf'),
Done

2022-12-13 08:26 UTC, vhugues commented on src/express-app.ts
> +		await options.http.beforeRoutingControllerLaunchHook(expressApp, log, options, conf);
Je préfèrerai que ce soit fait maintenant en même temps que d'autre breaking change.  
Mais si tu n'as pas le temps ce n'est pas grave

2022-12-13 08:37 UTC, vloic07 commented on src/init-conf.ts
> +			validationErrors: validationErrorsWithoutExcludeProperties,
J'ai ajouté le stringify. Ne pas oublier de faire ça dans le logger pour la suite et non ici.
Done

2022-12-13 10:44 UTC, vloic07 commented on src/express-app.ts
> +		await options.http.beforeRoutingControllerLaunchHook(expressApp, log, options, conf);
Done

2022-12-13 10:44 UTC, vloic07 commented on src/express-app.ts
> +		await options.http.afterRoutingControllerLaunchHook(expressApp, log, options, conf);
Done

2022-12-16 14:06 UTC, BenjD90 commented
Ajouter dans le README les gros changements en indiquant : 
* changement des paramètres du hook
* Node12 n'est plus supporté
* les labels du logger changent
* isEnable → isEnabled pour les options swagger

Ajouter un exemple avec un conf de 2 clées et leurs validateurs, 1 étant un secret.

2022-12-27 09:07 UTC, BenjD90 approved these changes

2022-12-27 09:08 UTC, merged